"""
car_profiles.py — Per-car tire pressure targets, temperature windows,
ride height limits, and engine layout notes.

Data sourced from iracing-setup-advisor (OblivionsPeak) and validated
against iRacing garage screens. 74 cars covered.

Usage:
    from core.car_profiles import get_car_profile, get_target_hot_psi
    psi = get_target_hot_psi("porsche_911_gt3_cup")
    # -> {"LF": 30.0, "RF": 30.0, "LR": 30.5, "RR": 30.5}
"""

# Auto-merged from iracing-setup-advisor car JSONs
# Keys are iRacing car path strings (lowercased)
CAR_PROFILES = {
    "acuraarx06gtp": {
        "name": "Acura ARX-06 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 similar setup philosophy to ARX-05",
    },
    "acura_arx_06": {
        "name": "Acura ARX-06 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 similar setup philosophy to ARX-05",
    },
    "acura_nsx_gt3": {
        "name": "Acura NSX GT3 EVO22",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine \u2014 hybrid system removed in GT3 trim; balanced weight distribution, good traction out of slow corners",
    },
    "acura_nsx_gt3_evo22": {
        "name": "Acura NSX GT3 Evo 22",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Updated Evo 22 spec; mid-rear engine gives better exit traction. More aerodynamic downforce than original NSX GT3.",
    },
    "alfa_romeo_giulia_tcr": {
        "name": "Alfa Romeo Giulia TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 fronts carry drive and braking loads, run 4\u20136 \u00b0C hotter than rears",
    },
    "alfaromeo_giulia_tcr": {
        "name": "Alfa Romeo Giulia TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 fronts carry drive and braking loads, run 4\u20136 \u00b0C hotter than rears",
    },
    "giulia_tcr": {
        "name": "Alfa Romeo Giulia TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 fronts carry drive and braking loads, run 4\u20136 \u00b0C hotter than rears",
    },
    "aston_martin_vantage_gt3": {
        "name": "Aston Martin Vantage GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 heavier car, fronts can build heat in slow corner sequences; rear tyre management important",
    },
    "aston_martin_vantage_gt4": {
        "name": "Aston Martin Vantage GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine RWD \u00e2\u20ac\u201d production-based GT4 spec. Narrower setup adjustability than GT3; tyre management is more important than outright pace.",
    },
    "audi_r8_lms_evo2": {
        "name": "Audi R8 LMS GT3 EVO II",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine with longitudinal layout \u2014 well-balanced tyre loads",
    },
    "audi_r8_gt3": {
        "name": "Audi R8 LMS GT3 EVO II",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine with longitudinal layout \u2014 well-balanced tyre loads",
    },
    "audi_r8_lms_gt4": {
        "name": "Audi R8 LMS GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Mid-engine \u00e2\u20ac\u201d very neutral tyre loading, one of the most forgiving GT4 cars. Equal front and rear target pressures suit the balanced weight distribution.",
    },
    "audi_rs3_lms_tcr": {
        "name": "Audi RS3 LMS TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 similar to Golf GTI TCR in layout and thermal characteristics",
    },
    "audirs3lms": {
        "name": "Audi RS3 LMS TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 similar to Golf GTI TCR in layout and thermal characteristics",
    },
    "rs3_lms_tcr": {
        "name": "Audi RS3 LMS TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.0, "RF": 33.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 similar to Golf GTI TCR in layout and thermal characteristics",
    },
    "bmw_m4_gt3": {
        "name": "BMW M4 GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 rears run slightly warmer due to drive load; fronts can overheat under hard braking",
    },
    "bmw_m4_gt4": {
        "name": "BMW M4 GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine RWD \u00e2\u20ac\u201d well-balanced GT4 with good mechanical grip. Fronts can overheat in heavy braking zones; watch inner-outer spread on front axle.",
    },
    "bmw_m6_gt3": {
        "name": "BMW M6 GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Legacy GT3 V8 BMW; heavier than M4 GT3, needs softer springs to compensate. Front-limited in slow corners.",
    },
    "bmw_m8_gte": {
        "name": "BMW M8 GTE",
        "class": "GTE",
        "target_hot_psi": {"LF": 27.5, "RF": 27.5, "LR": 26.5, "RR": 26.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 40, "RF": 40, "LR": 35, "RR": 35},
        "optimal_rh_mm": {"front_min": 50, "front_max": 70, "rear_min": 55, "rear_max": 75},
        "notes": "FR layout GTE \u00e2\u20ac\u201d wide front track, moderate rear bias typical of BMW GT cars",
    },
    "bmwm8gte": {
        "name": "BMW M8 GTE",
        "class": "GTE",
        "target_hot_psi": {"LF": 27.5, "RF": 27.5, "LR": 26.5, "RR": 26.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 40, "RF": 40, "LR": 35, "RR": 35},
        "optimal_rh_mm": {"front_min": 50, "front_max": 70, "rear_min": 55, "rear_max": 75},
        "notes": "FR layout GTE \u00e2\u20ac\u201d wide front track, moderate rear bias typical of BMW GT cars",
    },
    "bmwlmdh": {
        "name": "BMW M Hybrid V8 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 balanced weight distribution",
    },
    "bmw_m_hybrid_v8": {
        "name": "BMW M Hybrid V8 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 balanced weight distribution",
    },
    "bmw_z4_gt3": {
        "name": "BMW Z4 GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine GT3. Legacy model \u2014 replaced by M4 GT3. Prone to understeer on entry, sensitive to front ARB.",
    },
    "cadillacvseriesrgtp": {
        "name": "Cadillac V-Series.R GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 strong rear downforce package",
    },
    "cadillac_vseries_r": {
        "name": "Cadillac V-Series.R GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 strong rear downforce package",
    },
    "cadillac_v_series_r": {
        "name": "Cadillac V-Series.R GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh \u2014 strong rear downforce package",
    },
    "chevrolet_camaro_gt4r": {
        "name": "Chevrolet Camaro GT4.R",
        "class": "GT4",
        "target_hot_psi": {"LF": 30.5, "RF": 30.5, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "FR V8 muscle car in GT4 trim; strong straight-line but needs careful brake bias for rear stability. Runs hotter than European GT4 cars.",
    },
    "chevrolet_corvette_z06_gt3r": {
        "name": "Chevrolet Corvette Z06 GT3.R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine (C8) \u2014 neutral tyre loading; flat-plane V8 gives strong engine braking, factor into brake bias",
    },
    "chevrolet_corvette_z06_gt3": {
        "name": "Chevrolet Corvette Z06 GT3.R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine (C8) \u2014 neutral tyre loading; flat-plane V8 gives strong engine braking, factor into brake bias",
    },
    "dallaraf3": {
        "name": "Dallara F3",
        "class": "F3",
        "target_hot_psi": {"LF": 21.5, "RF": 21.5, "LR": 19.5, "RR": 19.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "Formula 3 \u2014 Hankook tyres, significant rear downforce, aero-sensitive setup",
    },
    "dallara_f3": {
        "name": "Dallara F3",
        "class": "F3",
        "target_hot_psi": {"LF": 21.5, "RF": 21.5, "LR": 19.5, "RR": 19.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "Formula 3 \u2014 Hankook tyres, significant rear downforce, aero-sensitive setup",
    },
    "dallara_ir01": {
        "name": "Dallara iR-01",
        "class": "Formula iRacing",
        "target_hot_psi": {"LF": 21.0, "RF": 21.0, "LR": 19.0, "RR": 19.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "iRacing's own formula car \u2014 balanced aero package",
    },
    "dallaraindycar": {
        "name": "Dallara IR05 IndyCar",
        "class": "IndyCar",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel \u2014 high downforce generates strong and even tyre loads",
    },
    "dallara_ir05": {
        "name": "Dallara IR05 IndyCar",
        "class": "IndyCar",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel \u2014 high downforce generates strong and even tyre loads",
    },
    "ir05": {
        "name": "Dallara IR05 IndyCar",
        "class": "IndyCar",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel \u2014 high downforce generates strong and even tyre loads",
    },
    "dallarair18": {
        "name": "Dallara IR18 (IndyCar)",
        "class": "IndyCar",
        "target_hot_psi": {"LF": 12.0, "RF": 12.0, "LR": 12.0, "RR": 12.0},
        "temp_min_c": 70,
        "temp_max_c": 100,
        "rear_temp_bias_c": 4.0,
        "notes": "Spec IndyCar \u2014 low tyre pressures; configs vary significantly road vs oval",
    },
    "dallara_ir18": {
        "name": "Dallara IR18 (IndyCar)",
        "class": "IndyCar",
        "target_hot_psi": {"LF": 12.0, "RF": 12.0, "LR": 12.0, "RR": 12.0},
        "temp_min_c": 70,
        "temp_max_c": 100,
        "rear_temp_bias_c": 4.0,
        "notes": "Spec IndyCar \u2014 low tyre pressures; configs vary significantly road vs oval",
    },
    "dallara_p217": {
        "name": "Dallara P217 LMP2",
        "class": "LMP2",
        "target_hot_psi": {"LF": 27.5, "RF": 27.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 2.0,
        "optimal_rh_mm": {"front_min": 45, "front_max": 65, "rear_min": 50, "rear_max": 70},
        "notes": "Open prototype \u2014 much higher aero and cornering loads than GT. Tyres heat quickly; front aero balance is critical. Runs slightly lower pressures than GT3 due to Michelin LMP compound.",
    },
    "ferrari_296_gt3": {
        "name": "Ferrari 296 GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine layout \u2014 relatively balanced tyre loading front to rear",
    },
    "ferrari_488_gt3": {
        "name": "Ferrari 488 GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-rear engine layout. Legacy GT3 \u2014 similar balance to 296 but heavier rear. High rear downforce sensitivity.",
    },
    "ferrari_488_gte": {
        "name": "Ferrari 488 GTE",
        "class": "GTE",
        "target_hot_psi": {"LF": 26.5, "RF": 26.5, "LR": 27.5, "RR": 27.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.5,
        "min_ride_height_mm": {"LF": 40, "RF": 40, "LR": 35, "RR": 35},
        "optimal_rh_mm": {"front_min": 50, "front_max": 70, "rear_min": 55, "rear_max": 75},
        "notes": "Mid-engine layout \u00e2\u20ac\u201d tail-happy under power, aggressive camber typical",
    },
    "ford_mustang_fr500s": {
        "name": "Ford Mustang FR500S",
        "class": "GT",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 75,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "optimal_rh_mm": {"front_min": 50, "front_max": 75, "rear_min": 55, "rear_max": 80},
        "notes": "Front-engine RWD GT car \u2014 watch front tyre wear under hard braking, monitor rear temperatures for overdriving on exit",
    },
    "ford_mustang_gt3": {
        "name": "Ford Mustang GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 flat-plane V8 characteristics; fronts work hard under braking, watch for front lock-up bias",
    },
    "ford_mustang_gt4": {
        "name": "Ford Mustang GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 30.5, "RF": 30.5, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "FR V8 GT4; heavier than most GT4 competitors, compensate with softer front springs. Brake bias sensitive.",
    },
    "ginetta_g55_gt4": {
        "name": "Ginetta G55 GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 27.5, "RR": 27.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine British GT car. Light and nimble, good mechanical grip. Less aero-dependent than continental GT4s.",
    },
    "ginetta_g56_gt4": {
        "name": "Ginetta G56 GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.5, "RF": 29.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Lightweight FR GT4; very responsive to setup changes. Low aero \u00e2\u20ac\u201d mechanical grip dominant. Good baseline balance.",
    },
    "honda_civic_type_r_tc": {
        "name": "Honda Civic Type R TC",
        "class": "TCR",
        "target_hot_psi": {"LF": 32.0, "RF": 32.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 1.0,
        "notes": "Front-wheel-drive TCR \u2014 front tyres carry significantly more load; camber critical on front axle",
    },
    "honda_civic_type_r": {
        "name": "Honda Civic Type R TC",
        "class": "TCR",
        "target_hot_psi": {"LF": 32.0, "RF": 32.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 1.0,
        "notes": "Front-wheel-drive TCR \u2014 front tyres carry significantly more load; camber critical on front axle",
    },
    "hyundai_elantra_n_gt4": {
        "name": "Hyundai Elantra N GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 1.5,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "FWD-based GT4 \u00e2\u20ac\u201d distinctive front-heavy thermal signature vs RWD GT4s; fronts run hotter",
    },
    "hyundai_elantra_n_tc": {
        "name": "Hyundai Elantra N TC",
        "class": "TCR",
        "target_hot_psi": {"LF": 32.0, "RF": 32.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 1.0,
        "notes": "FWD TCR \u2014 brake bias far forward, front tyres do majority of the work",
    },
    "hyundai_elantra_n": {
        "name": "Hyundai Elantra N TC",
        "class": "TCR",
        "target_hot_psi": {"LF": 32.0, "RF": 32.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 1.0,
        "notes": "FWD TCR \u2014 brake bias far forward, front tyres do majority of the work",
    },
    "tatuus_pm18": {
        "name": "Indy Pro 2000 (Tatuus PM-18)",
        "class": "Indy Pro 2000",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel ladder series \u2014 mid-level downforce, even tyre loads",
    },
    "indy_pro_2000": {
        "name": "Indy Pro 2000 (Tatuus PM-18)",
        "class": "Indy Pro 2000",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel ladder series \u2014 mid-level downforce, even tyre loads",
    },
    "pm18": {
        "name": "Indy Pro 2000 (Tatuus PM-18)",
        "class": "Indy Pro 2000",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 2.0,
        "notes": "Rear-engine open-wheel ladder series \u2014 mid-level downforce, even tyre loads",
    },
    "ktm_xbow_gt2": {
        "name": "KTM X-Bow GT2",
        "class": "GT2",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 4.0,
        "notes": "Mid/rear-engine layout \u2014 aggressive aero generates high rear tyre loads",
    },
    "ktmxbowgt2": {
        "name": "KTM X-Bow GT2",
        "class": "GT2",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 4.0,
        "notes": "Mid/rear-engine layout \u2014 aggressive aero generates high rear tyre loads",
    },
    "ktm_xbow_gt4": {
        "name": "KTM X-Bow GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.5,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Lightweight mid-engine GT4; highly sensitive to aero and ride height changes. Excellent rotation but requires careful downforce balance.",
    },
    "lamborghini_huracan_gt3_evo": {
        "name": "Lamborghini Hurac\u00e1n GT3 EVO",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine \u2014 slightly lower target pressures suit the softer sidewall construction",
    },
    "lamborghini_huracan_gt3": {
        "name": "Lamborghini Hurac\u00e1n GT3 EVO",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.0, "RF": 28.0, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine \u2014 slightly lower target pressures suit the softer sidewall construction",
    },
    "lamborghini_huracan_gt3_evo2": {
        "name": "Lamborghini Hurac\u00e1n GT3 EVO2",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine; responsive to rear ride height changes",
    },
    "lamborghini_huracan_evo2": {
        "name": "Lamborghini Hurac\u00e1n GT3 EVO2",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine; responsive to rear ride height changes",
    },
    "lamborghini_huracan_st_evo2": {
        "name": "Lamborghini Hurac\u00e1n Super Trofeo EVO2",
        "class": "GT3 Cup",
        "target_hot_psi": {"LF": 27.0, "RF": 27.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 4.0,
        "notes": "Mid-engine trophy car \u2014 spec Pirelli tyres",
    },
    "lamborghini_huracan_st": {
        "name": "Lamborghini Hurac\u00e1n Super Trofeo EVO2",
        "class": "GT3 Cup",
        "target_hot_psi": {"LF": 27.0, "RF": 27.0, "LR": 27.0, "RR": 27.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 4.0,
        "notes": "Mid-engine trophy car \u2014 spec Pirelli tyres",
    },
    "lexus_rc_f_gt3": {
        "name": "Lexus RC F GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "FR layout; watch brake balance for rear stability",
    },
    "ligier_js_f4": {
        "name": "Ligier JS F4",
        "class": "F4",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 21.0, "RR": 21.0},
        "temp_min_c": 70,
        "temp_max_c": 90,
        "rear_temp_bias_c": 0.0,
        "notes": "Open-wheel formula car \u2014 runs significantly lower pressures than GT. Tyres are very sensitive to temperature; narrow optimal window. Symmetric weight distribution so no natural front-rear temp bias.",
    },
    "ligier_js_p320": {
        "name": "Ligier JS P320 LMP3",
        "class": "LMP3",
        "target_hot_psi": {"LF": 20.5, "RF": 20.5, "LR": 20.5, "RR": 20.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 3.0,
        "notes": "LMP3 spec car \u2014 Michelin slicks, narrower setup window than LMP2",
    },
    "maserati_mc_gt4": {
        "name": "Maserati MC GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine RWD \u00e2\u20ac\u201d long wheelbase gives stability but reduces rotation in slow corners. Benefits from rear toe-in to help rotation.",
    },
    "mazda_mx5_cup": {
        "name": "Mazda MX-5 Cup",
        "class": "Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 70,
        "temp_max_c": 90,
        "rear_temp_bias_c": 1.0,
        "notes": "Lightweight RWD \u2014 limited setup adjustability; tyre management is key",
    },
    "mclaren_570s_gt4": {
        "name": "McLaren 570S GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Mid-engine \u00e2\u20ac\u201d even tyre loading across all four corners. Responsive to camber changes; small adjustments have a noticeable effect.",
    },
    "mclaren_720s_gt3_evo": {
        "name": "McLaren 720S GT3 EVO",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine \u2014 excellent rotation but can be snappy on exit; balanced tyre loading",
    },
    "mclaren_720s_gt3": {
        "name": "McLaren 720S GT3 EVO",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Mid-engine \u2014 excellent rotation but can be snappy on exit; balanced tyre loading",
    },
    "mercedes_amg_gt2": {
        "name": "Mercedes-AMG GT2",
        "class": "GT2",
        "target_hot_psi": {"LF": 31.0, "RF": 31.0, "LR": 30.5, "RR": 30.5},
        "temp_min_c": 80,
        "temp_max_c": 105,
        "rear_temp_bias_c": 2.5,
        "notes": "Front-engine GT2 \u2014 higher power than GT3, significant aero. Run higher pressures than GT3 AMG.",
    },
    "mercedes_amg_gt3_2020": {
        "name": "Mercedes-AMG GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 fronts can build excess heat in long braking zones",
    },
    "mercedes_amg_gt3": {
        "name": "Mercedes-AMG GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 fronts can build excess heat in long braking zones",
    },
    "mercedes_amg_gt4": {
        "name": "Mercedes-AMG GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine RWD \u00e2\u20ac\u201d heavier GT4 entry; benefits from slightly more front camber to manage heat in long corners.",
    },
    "nascarcwts": {
        "name": "NASCAR Camping World Truck",
        "class": "NASCAR Truck",
        "target_hot_psi": {"LF": 21.0, "RF": 22.0, "LR": 21.0, "RR": 22.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD pickup \u2014 higher body/aero drag than Cup; slightly lower tyre loads",
    },
    "nascar_camping_world_truck": {
        "name": "NASCAR Camping World Truck",
        "class": "NASCAR Truck",
        "target_hot_psi": {"LF": 21.0, "RF": 22.0, "LR": 21.0, "RR": 22.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD pickup \u2014 higher body/aero drag than Cup; slightly lower tyre loads",
    },
    "nascar_truck": {
        "name": "NASCAR Camping World Truck",
        "class": "NASCAR Truck",
        "target_hot_psi": {"LF": 21.0, "RF": 22.0, "LR": 21.0, "RR": 22.0},
        "temp_min_c": 80,
        "temp_max_c": 110,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD pickup \u2014 higher body/aero drag than Cup; slightly lower tyre loads",
    },
    "nascarnextgen_xfinity_chevrolet": {
        "name": "NASCAR Xfinity Chevrolet Camaro",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 track stagger and banking loads strongly favour right-side tyres on ovals",
    },
    "xfinity_chevrolet": {
        "name": "NASCAR Xfinity Chevrolet Camaro",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 track stagger and banking loads strongly favour right-side tyres on ovals",
    },
    "nascar_xfinity_chevrolet": {
        "name": "NASCAR Xfinity Chevrolet Camaro",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 track stagger and banking loads strongly favour right-side tyres on ovals",
    },
    "nascarnextgen_xfinity_ford": {
        "name": "NASCAR Xfinity Ford Mustang",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 same tyre targets as other Xfinity models; manufacturer cosmetic only",
    },
    "xfinity_ford": {
        "name": "NASCAR Xfinity Ford Mustang",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 same tyre targets as other Xfinity models; manufacturer cosmetic only",
    },
    "nascar_xfinity_ford": {
        "name": "NASCAR Xfinity Ford Mustang",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 same tyre targets as other Xfinity models; manufacturer cosmetic only",
    },
    "nascarnextgen_xfinity_toyota": {
        "name": "NASCAR Xfinity Toyota Supra",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 identical spec to other Xfinity models",
    },
    "xfinity_toyota": {
        "name": "NASCAR Xfinity Toyota Supra",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 identical spec to other Xfinity models",
    },
    "nascar_xfinity_toyota": {
        "name": "NASCAR Xfinity Toyota Supra",
        "class": "NASCAR Xfinity",
        "target_hot_psi": {"LF": 22.0, "RF": 23.0, "LR": 22.0, "RR": 23.0},
        "temp_min_c": 80,
        "temp_max_c": 108,
        "rear_temp_bias_c": 1.0,
        "notes": "Oval-spec RWD \u2014 identical spec to other Xfinity models",
    },
    "nascarnextgen_chevrolet": {
        "name": "NASCAR Cup Series Chevrolet Camaro ZL1",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 road course setup differs significantly from oval; crossweight critical on ovals",
    },
    "nascar_nextgen_chevrolet": {
        "name": "NASCAR Cup Series Chevrolet Camaro ZL1",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 road course setup differs significantly from oval; crossweight critical on ovals",
    },
    "nascarnextgen_ford": {
        "name": "NASCAR Cup Series Ford Mustang",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 same chassis as Chevy/Toyota, different aero package",
    },
    "nascar_nextgen_ford": {
        "name": "NASCAR Cup Series Ford Mustang",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 same chassis as Chevy/Toyota, different aero package",
    },
    "nascarnextgen_toyota": {
        "name": "NASCAR Cup Series Toyota Camry XSE",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 spec Goodyear tyres across all three manufacturers",
    },
    "nascar_nextgen_toyota": {
        "name": "NASCAR Cup Series Toyota Camry XSE",
        "class": "NASCAR Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 70,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "NASCAR Next Gen \u2014 spec Goodyear tyres across all three manufacturers",
    },
    "nissangtrnismo_gt3": {
        "name": "Nissan GT-R Nismo GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 29.5, "RF": 29.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "FR GT-R-based platform; stable understeer tendency, good traction. Watch front left tyre loading in long fast corners.",
    },
    "porsche_718_cayman_gt4_clubsport_mr": {
        "name": "Porsche 718 Cayman GT4 Clubsport",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.5, "RF": 29.5, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 4.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Mid-rear engine (flat-4 behind rear axle) \u00e2\u20ac\u201d similar rear-bias characteristics to the 911 but less extreme. Naturally good rotation; can be prone to snap oversteer if rear pressures are too low.",
    },
    "porsche_718_cayman_gt4_rs_clubsport": {
        "name": "Porsche 718 GT4 RS Clubsport",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Mid-engine GT4 RS. Higher downforce than standard Cayman GT4, stiffer chassis. Rear-engine weight bias.",
    },
    "718gt4rsclubsport": {
        "name": "Porsche 718 GT4 RS Clubsport",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Mid-engine GT4 RS. Higher downforce than standard Cayman GT4, stiffer chassis. Rear-engine weight bias.",
    },
    "porsche_911_gt3_cup": {
        "name": "Porsche 911 GT3 Cup (992)",
        "class": "Porsche Cup",
        "target_hot_psi": {"LF": 30.0, "RF": 30.0, "LR": 30.5, "RR": 30.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 5.0,
        "min_ride_height_mm": {"LF": 50, "RF": 50, "LR": 45, "RR": 45},
        "notes": "Rear-engine spec cup car \u00e2\u20ac\u201d limited adjustability compared to GT3R. Runs higher cold pressures on cup-spec Michelin slicks. Rear temp bias same as GT3R due to identical engine layout.",
    },
    "porsche992rgt3": {
        "name": "Porsche 911 GT3R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Rear-engine layout \u2014 rears naturally run ~5 \u00b0C hotter than fronts in a balanced setup",
    },
    "porsche_992gt3r": {
        "name": "Porsche 911 GT3R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Rear-engine layout \u2014 rears naturally run ~5 \u00b0C hotter than fronts in a balanced setup",
    },
    "porsche_911gt3r_992": {
        "name": "Porsche 911 GT3R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Rear-engine layout \u2014 rears naturally run ~5 \u00b0C hotter than fronts in a balanced setup",
    },
    "porsche_911gt3r": {
        "name": "Porsche 911 GT3R",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Rear-engine layout \u2014 rears naturally run ~5 \u00b0C hotter than fronts in a balanced setup",
    },
    "porsche_911_rsr": {
        "name": "Porsche 911 RSR",
        "class": "GTE",
        "target_hot_psi": {"LF": 27.5, "RF": 27.5, "LR": 28.0, "RR": 28.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 6.0,
        "min_ride_height_mm": {"LF": 40, "RF": 40, "LR": 35, "RR": 35},
        "optimal_rh_mm": {"front_min": 50, "front_max": 70, "rear_min": 55, "rear_max": 75},
        "notes": "Rear-engine layout \u00e2\u20ac\u201d rear tyres work significantly harder; higher rear PSI and rear_weight_bias_c reflects this",
    },
    "porsche935": {
        "name": "Porsche 935",
        "class": "GTO",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 31.0, "RR": 31.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "notes": "Rear-engine RWD \u2014 iconic flat-6 turbo layout pushes significant load onto rear tyres",
    },
    "porsche_935": {
        "name": "Porsche 935",
        "class": "GTO",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 31.0, "RR": 31.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 5.0,
        "notes": "Rear-engine RWD \u2014 iconic flat-6 turbo layout pushes significant load onto rear tyres",
    },
    "porsche963gtp": {
        "name": "Porsche 963 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh hybrid prototype \u2014 front-heavy braking, high rear downforce",
    },
    "porsche_963": {
        "name": "Porsche 963 GTP",
        "class": "GTP",
        "target_hot_psi": {"LF": 23.0, "RF": 23.0, "LR": 23.0, "RR": 23.0},
        "temp_min_c": 85,
        "temp_max_c": 110,
        "rear_temp_bias_c": 5.0,
        "optimal_rh_mm": {"front_min": 40, "front_max": 65, "rear_min": 45, "rear_max": 70},
        "notes": "LMDh hybrid prototype \u2014 front-heavy braking, high rear downforce",
    },
    "radical_sr10": {
        "name": "Radical SR10",
        "class": "Radical",
        "target_hot_psi": {"LF": 21.0, "RF": 21.0, "LR": 17.0, "RR": 17.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "Mid-engine sports prototype \u2014 very light, mechanically demanding",
    },
    "radical_sr8": {
        "name": "Radical SR8",
        "class": "Radical",
        "target_hot_psi": {"LF": 20.0, "RF": 20.0, "LR": 16.0, "RR": 16.0},
        "temp_min_c": 70,
        "temp_max_c": 90,
        "rear_temp_bias_c": 2.0,
        "notes": "Motorcycle-derived V8, very high power-to-weight. Rear-limited under traction. Run lower pressures than SR10.",
    },
    "ray_ff1600": {
        "name": "Ray FF1600",
        "class": "FF1600",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 20.0, "RR": 20.0},
        "temp_min_c": 75,
        "temp_max_c": 90,
        "rear_temp_bias_c": 1.0,
        "notes": "Naturally aspirated formula car \u2014 mechanical grip focused, no aero",
    },
    "skipbarber_f2000": {
        "name": "Skip Barber Formula 2000",
        "class": "Formula",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 20.0, "RR": 20.0},
        "temp_min_c": 75,
        "temp_max_c": 90,
        "rear_temp_bias_c": 1.5,
        "notes": "Classic iRacing entry-level formula car",
    },
    "skipbarber": {
        "name": "Skip Barber Formula 2000",
        "class": "Formula",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 20.0, "RR": 20.0},
        "temp_min_c": 75,
        "temp_max_c": 90,
        "rear_temp_bias_c": 1.5,
        "notes": "Classic iRacing entry-level formula car",
    },
    "super_formula_sf23": {
        "name": "Super Formula SF23",
        "class": "Super Formula",
        "target_hot_psi": {"LF": 20.5, "RF": 20.5, "LR": 18.5, "RR": 18.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "notes": "Japanese Super Formula \u2014 high downforce, Yokohama tyres, rear-heavy aero",
    },
    "dallarasf23": {
        "name": "Super Formula SF23",
        "class": "Super Formula",
        "target_hot_psi": {"LF": 20.5, "RF": 20.5, "LR": 18.5, "RR": 18.5},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 3.0,
        "notes": "Japanese Super Formula \u2014 high downforce, Yokohama tyres, rear-heavy aero",
    },
    "tatuus_f4": {
        "name": "Tatuus F4",
        "class": "F4",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 20.0, "RR": 20.0},
        "temp_min_c": 75,
        "temp_max_c": 90,
        "rear_temp_bias_c": 2.0,
        "notes": "Formula 4 entry-level spec \u2014 limited setup adjustability",
    },
    "tatuus_pm18": {
        "name": "Tatuus F4",
        "class": "F4",
        "target_hot_psi": {"LF": 22.0, "RF": 22.0, "LR": 20.0, "RR": 20.0},
        "temp_min_c": 75,
        "temp_max_c": 90,
        "rear_temp_bias_c": 2.0,
        "notes": "Formula 4 entry-level spec \u2014 limited setup adjustability",
    },
    "toyota_gr86_cup": {
        "name": "Toyota GR86 Cup",
        "class": "Cup",
        "target_hot_psi": {"LF": 31.0, "RF": 31.0, "LR": 30.0, "RR": 30.0},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "notes": "Cup-spec street-derived tyre \u2014 narrower temperature window than GT3; runs higher cold pressures",
    },
    "toyota_gr_supra_gt3": {
        "name": "Toyota GR Supra GT3",
        "class": "GT3",
        "target_hot_psi": {"LF": 28.5, "RF": 28.5, "LR": 29.0, "RR": 29.0},
        "temp_min_c": 80,
        "temp_max_c": 100,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 35, "RF": 35, "LR": 30, "RR": 30},
        "optimal_rh_mm": {"front_min": 55, "front_max": 75, "rear_min": 60, "rear_max": 80},
        "notes": "Front-engine RWD \u2014 well-balanced chassis; rears take drive load, fronts can overheat in heavy braking zones",
    },
    "toyota_gr_supra_gt4": {
        "name": "Toyota GR Supra GT4",
        "class": "GT4",
        "target_hot_psi": {"LF": 29.0, "RF": 29.0, "LR": 29.5, "RR": 29.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": 2.0,
        "min_ride_height_mm": {"LF": 25, "RF": 25, "LR": 20, "RR": 20},
        "notes": "Front-engine RWD \u00e2\u20ac\u201d one of the more adjustable GT4 platforms. Good baseline balance; responds well to spring rate changes.",
    },
    "vw_golf_gti_tcr": {
        "name": "Volkswagen Golf GTI TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.5, "RF": 33.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 significant front tyre load bias; rear temps naturally lower",
    },
    "vwgolfgtitcr": {
        "name": "Volkswagen Golf GTI TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.5, "RF": 33.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 significant front tyre load bias; rear temps naturally lower",
    },
    "golf_gti_tcr": {
        "name": "Volkswagen Golf GTI TCR",
        "class": "TCR",
        "target_hot_psi": {"LF": 33.5, "RF": 33.5, "LR": 28.5, "RR": 28.5},
        "temp_min_c": 75,
        "temp_max_c": 95,
        "rear_temp_bias_c": -4.0,
        "notes": "FF touring car \u2014 significant front tyre load bias; rear temps naturally lower",
    },
}


def get_car_profile(car_name: str) -> dict:
    """
    Look up a car profile by iRacing car name string.
    Tries exact match first, then token overlap.
    Returns empty dict if no match.
    """
    import re as _re
    key = car_name.lower().strip()
    if key in CAR_PROFILES:
        return CAR_PROFILES[key]
    # Try stripping spaces/underscores
    norm = _re.sub(r"[^a-z0-9]", "", key)
    for k, v in CAR_PROFILES.items():
        if _re.sub(r"[^a-z0-9]", "", k) == norm:
            return v
    # Token overlap fallback
    tokens = set(_re.findall(r"[a-z0-9]+", key))
    best, best_score = {}, 0
    for k, v in CAR_PROFILES.items():
        k_tokens = set(_re.findall(r"[a-z0-9]+", k))
        score = len(tokens & k_tokens)
        if score > best_score:
            best_score = score
            best = v
    return best if best_score >= 2 else {}


def get_target_hot_psi(car_name: str) -> dict:
    """Return {LF, RF, LR, RR} target hot pressure dict for a car."""
    profile = get_car_profile(car_name)
    return profile.get("target_hot_psi", {"LF": 29.0, "RF": 29.0, "LR": 29.0, "RR": 29.0})


def get_tire_temp_range(car_name: str) -> tuple:
    """Return (min_c, max_c) optimal tire temperature range for a car."""
    profile = get_car_profile(car_name)
    return profile.get("temp_min_c", 80), profile.get("temp_max_c", 100)


def get_min_ride_heights(car_name: str) -> dict:
    """Return minimum legal ride height dict {LF, RF, LR, RR} in mm."""
    profile = get_car_profile(car_name)
    return profile.get("min_ride_height_mm", {})